# Generated by Django 4.2.7 on 2026-08-27 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysession',
            name='entered_by',
            field=models.ForeignKey(blank=True, help_text='Admin who manually created this session. Blank for sessions that arrived automatically via the sync API.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_sessions_entered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitysession',
            name='is_manual_entry',
            field=models.BooleanField(default=False, help_text='True if this session was hand-entered by an admin in the admin panel instead of synced automatically from the GapsSight desktop app.'),
        ),
    ]
