# Generated by Django 4.2.7 on 2026-08-30 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('failed_login', 'Failed login'), ('brute_force', 'Brute-force login attempt'), ('sql_injection', 'SQL injection attempt'), ('xss', 'Cross-site scripting (XSS) attempt'), ('path_traversal', 'Path traversal attempt'), ('command_injection', 'Command injection attempt'), ('suspicious_agent', 'Known scanner / exploit-tool user agent'), ('sensitive_path_probe', 'Sensitive path probing (404 scanning)'), ('csrf_failure', 'CSRF validation failure'), ('unauthorized_access', 'Unauthorized access attempt'), ('other', 'Other')], default='other', max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('false_positive', 'False positive')], default='new', max_length=20)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('username_attempted', models.CharField(blank=True, default='', help_text="Raw username submitted, even if it doesn't match any account.", max_length=150)),
                ('path', models.CharField(blank=True, default='', max_length=500)),
                ('method', models.CharField(blank=True, default='', max_length=10)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('summary', models.CharField(help_text='One-line human-readable description shown in lists and the report card.', max_length=255)),
                ('details', models.TextField(blank=True, default='', help_text='Extra context -- the matched pattern, request params (sanitised), attempt count, etc.')),
                ('occurrence_count', models.PositiveIntegerField(default=1, help_text='How many raw attempts this row represents (used by brute-force de-duplication).')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Set only if the request was tied to a known account (e.g. a failed login for a real username).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security event',
                'verbose_name_plural': 'Security events',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='security_se_event_t_18b5ea_idx'), models.Index(fields=['severity', 'status'], name='security_se_severit_ce8926_idx'), models.Index(fields=['source_ip', 'created_at'], name='security_se_source__79b9a6_idx')],
            },
        ),
    ]
